@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package sturdycobble.createrevision.api.depot_recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;