@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package sturdycobble.createrevision.api.heat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;