@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package sturdycobble.createrevision.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;