@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package sturdycobble.createrevision.utils;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;