@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.sturdycobble.createrevision.api.heat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;