@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package sturdycobble.createrevision.contents.custom_fan;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;