@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.sturdycobble.createrevision.contents.heat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;